name: lerobot_image

# make sure the shape_meta contains a subset of the corresponding zarr dataset
# it doens't have to contain element, but each key and shape should match 
# only images from cameras aer rgb, everything else is low dim

shape_meta: &shape_meta
  obs:
    follower_joint_pos:           
      shape: [6]
      type: low_dim
    camera:             
      shape: [3, 240, 320]
      type: rgb
  action:
    shape: [6]

dataset:
  _target_: diffusion_policy.dataset.omnid_image_dataset.OmnidImageDataset
  zarr_path: ???
  shape_meta: *shape_meta
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null

env_runner:
  _target_: diffusion_policy.env_runner.omnid_image_runner.OmnidImageRunner
  output_dir: ???
