name: omnid_image

# config parameters for the dataset
horizon: 16
n_obs_steps: 2
n_action_steps: 8

shape_meta:
  obs:
    camera:
      shape: [3, 480, 640] # need to modify based on actual camera data
      type: rgb
    agent_pos:
      shape: [9]          # gimbal_pos(9) + base_twist(9)
      type: low_dim
  action:
    shape: [9]             # global mode, [3] for local mode

dataset:
  _target_: diffusion_policy.dataset.omnid_image_dataset.OmnidImageDataset
  zarr_path: ???
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null

env_runner:
  _target_: diffusion_policy.env_runner.omnid_image_runner.OmnidImageRunner
  output_dir: ???